"""document_storage_fields

Revision ID: 8eb51db4f492
Revises: 12c54b5b47a3
Create Date: 2026-06-14 18:35:57.337213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb51db4f492'
down_revision: Union[str, None] = '12c54b5b47a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default per non rompere le righe esistenti (documents è popolata)
    op.add_column('documents', sa.Column('storage_uri', sa.String(), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('size_bytes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('sha256', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'sha256')
    op.drop_column('documents', 'size_bytes')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'storage_uri')
    # ### end Alembic commands ###
