"""baseline

Revision ID: 12c54b5b47a3
Revises: 
Create Date: 2026-06-14 18:22:45.129263
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c54b5b47a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_tax_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('referent', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('next_deadline', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_form', sa.String(), nullable=False),
    sa.Column('company_type', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('vat', sa.String(), nullable=False),
    sa.Column('rea', sa.String(), nullable=False),
    sa.Column('cciaa', sa.String(), nullable=False),
    sa.Column('pec', sa.String(), nullable=False),
    sa.Column('legal_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('constitution_date', sa.String(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=False),
    sa.Column('ateco', sa.String(), nullable=False),
    sa.Column('fatturato', sa.Float(), nullable=False),
    sa.Column('dipendenti', sa.Integer(), nullable=False),
    sa.Column('patrimonio_netto', sa.Float(), nullable=False),
    sa.Column('anno_bilancio', sa.String(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_exposures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('intermediary', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('accordato', sa.Float(), nullable=False),
    sa.Column('utilizzato', sa.Float(), nullable=False),
    sa.Column('importo_garantito', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('reference_month', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_report_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('period_from', sa.String(), nullable=False),
    sa.Column('period_to', sa.String(), nullable=False),
    sa.Column('most_recent_month', sa.String(), nullable=False),
    sa.Column('num_intermediaries', sa.Integer(), nullable=False),
    sa.Column('total_exposure', sa.Float(), nullable=False),
    sa.Column('total_guarantees', sa.Float(), nullable=False),
    sa.Column('has_sofferenze', sa.Boolean(), nullable=False),
    sa.Column('has_criticita', sa.Boolean(), nullable=False),
    sa.Column('criticita', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('crosscheck_status', sa.String(), nullable=False),
    sa.Column('crosscheck_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debt_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('creditor_name', sa.String(), nullable=False),
    sa.Column('debt_type', sa.String(), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('residual_amount', sa.Float(), nullable=False),
    sa.Column('overdue_amount', sa.Float(), nullable=False),
    sa.Column('monthly_installment', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debtors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('birth_place', sa.String(), nullable=False),
    sa.Column('residence', sa.String(), nullable=False),
    sa.Column('domicile', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pec', sa.String(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.Column('employer', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('household_composition', sa.Text(), nullable=False),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('monthly_net_income', sa.Float(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('income_sources', sa.Text(), nullable=False),
    sa.Column('monthly_expenses', sa.Float(), nullable=False),
    sa.Column('rent_or_mortgage', sa.Float(), nullable=False),
    sa.Column('bank_accounts', sa.Text(), nullable=False),
    sa.Column('has_ongoing_garnishment', sa.Boolean(), nullable=False),
    sa.Column('has_salary_assignment', sa.Boolean(), nullable=False),
    sa.Column('has_payment_delegation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('openapi_request_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('mapped_data', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantees_given',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('intermediary', sa.String(), nullable=False),
    sa.Column('guaranteed_subject', sa.String(), nullable=False),
    sa.Column('valore_garanzia', sa.Float(), nullable=False),
    sa.Column('importo_garantito', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cadastral_data', sa.String(), nullable=False),
    sa.Column('ownership_share', sa.String(), nullable=False),
    sa.Column('ownership_right', sa.String(), nullable=False),
    sa.Column('surface_mq', sa.Float(), nullable=False),
    sa.Column('cadastral_income', sa.Float(), nullable=False),
    sa.Column('cadastral_value', sa.Float(), nullable=False),
    sa.Column('commercial_value', sa.Float(), nullable=False),
    sa.Column('is_primary_residence', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('other_owners', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('has_mortgage', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_debt_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('owner_kind', sa.String(), nullable=False),
    sa.Column('debtor_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('codice_fiscale', sa.String(), nullable=False),
    sa.Column('denominazione', sa.String(), nullable=False),
    sa.Column('data_elaborazione', sa.String(), nullable=False),
    sa.Column('total_residuo', sa.Float(), nullable=False),
    sa.Column('total_residuo_netto', sa.Float(), nullable=False),
    sa.Column('total_carico_affidato', sa.Float(), nullable=False),
    sa.Column('count_proc_attive', sa.Integer(), nullable=False),
    sa.Column('quadrature_ok', sa.Boolean(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('cf_mismatch', sa.Boolean(), nullable=False),
    sa.Column('raw_extraction', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('make_model', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_code', sa.String(), nullable=False),
    sa.Column('is_client', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('is_legal_rep', sa.Boolean(), nullable=False),
    sa.Column('quota_value', sa.Float(), nullable=False),
    sa.Column('quota_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('ocr_provider', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('json_output', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('fiscal_year_end', sa.String(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('ateco', sa.String(), nullable=False),
    sa.Column('raw_extraction', sa.JSON(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('total_debts', sa.Float(), nullable=False),
    sa.Column('revenues', sa.Float(), nullable=False),
    sa.Column('net_result', sa.Float(), nullable=False),
    sa.Column('debts_secured', sa.Boolean(), nullable=False),
    sa.Column('privileged_debts', sa.Float(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('crosscheck_status', sa.String(), nullable=False),
    sa.Column('crosscheck_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_debt_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('ente_creditore', sa.String(), nullable=False),
    sa.Column('ente_categoria', sa.String(), nullable=False),
    sa.Column('data_notifica', sa.String(), nullable=False),
    sa.Column('carico_affidato', sa.Float(), nullable=False),
    sa.Column('sgravio', sa.Float(), nullable=False),
    sa.Column('gia_pagato', sa.Float(), nullable=False),
    sa.Column('stralcio', sa.Float(), nullable=False),
    sa.Column('residuo_carico', sa.Float(), nullable=False),
    sa.Column('interessi_mora', sa.Float(), nullable=False),
    sa.Column('oneri_diritti', sa.Float(), nullable=False),
    sa.Column('totale_residuo', sa.Float(), nullable=False),
    sa.Column('importo_sospeso', sa.Float(), nullable=False),
    sa.Column('totale_residuo_netto', sa.Float(), nullable=False),
    sa.Column('rateizzato', sa.Boolean(), nullable=False),
    sa.Column('proc_attive', sa.Boolean(), nullable=False),
    sa.Column('def_agevolata', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['tax_debt_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('value_cur', sa.Float(), nullable=True),
    sa.Column('value_prev', sa.Float(), nullable=True),
    sa.Column('fmt', sa.String(), nullable=False),
    sa.Column('trend', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_indicators')
    op.drop_table('tax_debt_items')
    op.drop_table('financial_statements')
    op.drop_table('extractions')
    op.drop_table('company_members')
    op.drop_table('vehicles')
    op.drop_table('tax_debt_statements')
    op.drop_table('real_estates')
    op.drop_table('guarantees_given')
    op.drop_table('enrichment_requests')
    op.drop_table('documents')
    op.drop_table('debtors')
    op.drop_table('debt_positions')
    op.drop_table('creditors')
    op.drop_table('credit_report_summaries')
    op.drop_table('credit_exposures')
    op.drop_table('companies')
    op.drop_table('cases')
    op.drop_table('organizations')
    # ### end Alembic commands ###
