"""field_edits_audit

Revision ID: de39e059c52c
Revises: 21dc561e08b3
Create Date: 2026-06-14 19:55:44.409992
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de39e059c52c'
down_revision: Union[str, None] = '21dc561e08b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_edits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_edits_case_id'), 'field_edits', ['case_id'], unique=False)
    op.create_index(op.f('ix_field_edits_entity_id'), 'field_edits', ['entity_id'], unique=False)
    op.create_index(op.f('ix_field_edits_entity_type'), 'field_edits', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_edits_entity_type'), table_name='field_edits')
    op.drop_index(op.f('ix_field_edits_entity_id'), table_name='field_edits')
    op.drop_index(op.f('ix_field_edits_case_id'), table_name='field_edits')
    op.drop_table('field_edits')
    # ### end Alembic commands ###
