"""financial_raw_corrected

Revision ID: 6f1aa56b9e85
Revises: de39e059c52c
Create Date: 2026-06-14 20:07:36.449914
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1aa56b9e85'
down_revision: Union[str, None] = 'de39e059c52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_statements', sa.Column('raw_corrected', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_statements', 'raw_corrected')
    # ### end Alembic commands ###
