"""cross_case_index_accesslog

Revision ID: 21dc561e08b3
Revises: e84180f2d37b
Create Date: 2026-06-14 18:45:26.979704
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dc561e08b3'
down_revision: Union[str, None] = 'e84180f2d37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('cf', sa.String(), nullable=False),
    sa.Column('from_case_id', sa.String(), nullable=False),
    sa.Column('to_case_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_cf'), 'access_logs', ['cf'], unique=False)
    op.create_index(op.f('ix_cases_client_tax_code'), 'cases', ['client_tax_code'], unique=False)
    op.create_index(op.f('ix_companies_tax_code'), 'companies', ['tax_code'], unique=False)
    op.create_index(op.f('ix_companies_vat'), 'companies', ['vat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_vat'), table_name='companies')
    op.drop_index(op.f('ix_companies_tax_code'), table_name='companies')
    op.drop_index(op.f('ix_cases_client_tax_code'), table_name='cases')
    op.drop_index(op.f('ix_access_logs_cf'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
