"""persistence_created_at_source

Revision ID: e84180f2d37b
Revises: 8eb51db4f492
Create Date: 2026-06-14 18:41:46.265509
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84180f2d37b'
down_revision: Union[str, None] = '8eb51db4f492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default su tabelle popolate: now() per le date, 'manuale' per la provenienza.
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('credit_exposures', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('credit_report_summaries', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('creditors', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('debt_positions', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('guarantees_given', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('real_estates', sa.Column('source', sa.String(), nullable=False, server_default='manuale'))
    op.add_column('real_estates', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('vehicles', sa.Column('source', sa.String(), nullable=False, server_default='manuale'))
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'source')
    op.drop_column('real_estates', 'created_at')
    op.drop_column('real_estates', 'source')
    op.drop_column('guarantees_given', 'created_at')
    op.drop_column('debt_positions', 'created_at')
    op.drop_column('creditors', 'created_at')
    op.drop_column('credit_report_summaries', 'created_at')
    op.drop_column('credit_exposures', 'created_at')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
